project:
  title: "Pythia's Advice"
  type: manuscript

manuscript:
  article: EAISI-Pythia.qmd
  
editor: visual

format:
  html: 
    toc: true
    comments:
      hypothesis: true  
    theme: solar
  jss-pdf:
    keep-tex: true 
    journal:
      type: article 
      cite-shortnames: false
      suppress: 
      include-jss-default: true    
  pdf: default
  typst: default

execute:
  freeze: auto
